import fs from 'node:fs';
const path='src/both.jsx';
let s=fs.readFileSync(path,'utf8');
if(s.includes('LIVE_COSTS_V1')){console.log('Live costs already patched');process.exit(0)}
const anchor="const DUAL_RISK_GUARDS_V1={scalpLossBlockMs:15*60*1000,momentumLossBlockMs:30*60*1000};";
if(!s.includes(anchor))throw new Error('risk config anchor not found');
s=s.replace(anchor,anchor+"\nconst LIVE_COSTS_V1={taker:0.0005,gst:0.18,slippagePerSide:0.0002,fundingPer8h:0.0001};\nconst feeOnNotional=n=>num(n)*LIVE_COSTS_V1.taker*(1+LIVE_COSTS_V1.gst);\nfunction netClose(p,exit,gross,now=Date.now()){const en=Math.abs(num(p.entry)*num(p.qty)),xn=Math.abs(num(exit)*num(p.qty)),fees=feeOnNotional(en+xn),slippage=(en+xn)*LIVE_COSTS_V1.slippagePerSide,hours=Math.max(0,(now-new Date(p.openedAt).getTime())/3600000),funding=en*LIVE_COSTS_V1.fundingPer8h*(hours/8);return{grossPnl:gross,fees,slippage,funding,pnl:gross-fees-slippage-funding};}\nfunction costAdjustedOpenPnl(p,px){const gross=(p.side==='LONG'?px-p.entry:p.entry-px)*p.qty,en=Math.abs(num(p.entry)*num(p.qty)),xn=Math.abs(num(px)*num(p.qty)),hours=Math.max(0,(Date.now()-new Date(p.openedAt).getTime())/3600000);return gross-feeOnNotional(en+xn)-(en+xn)*LIVE_COSTS_V1.slippagePerSide-en*LIVE_COSTS_V1.fundingPer8h*(hours/8);}");
s=s.replace("const exit=finalTp,pnl=(long?exit-p.entry:p.entry-exit)*p.qty;closed.push({...p,exit,pnl,closedAt:new Date().toISOString(),exitReason:'FINAL TP',execution:'Final 2R'});return null","const exit=finalTp,gross=(long?exit-p.entry:p.entry-exit)*p.qty,cost=netClose(p,exit,gross);closed.push({...p,exit,...cost,closedAt:new Date().toISOString(),exitReason:'FINAL TP',execution:'Final 2R'});return null");
s=s.replace("const exit=sl,pnl=(long?exit-p.entry:p.entry-exit)*p.qty;closed.push({...p,exit,pnl,closedAt:new Date().toISOString(),exitReason:'SL',execution:'Initial SL'});if(pnl<0)blocks","const exit=sl,gross=(long?exit-p.entry:p.entry-exit)*p.qty,cost=netClose(p,exit,gross);closed.push({...p,exit,...cost,closedAt:new Date().toISOString(),exitReason:'SL',execution:'Initial SL'});if(cost.pnl<0)blocks");
s=s.replace("const exit=sl,pnl=(long?exit-p.entry:p.entry-exit)*p.qty;closed.push({...p,exit,pnl,closedAt:new Date().toISOString(),exitReason:'LOCK/ATR TRAIL',execution:'Trailing SL after TP1'});return null","const exit=sl,gross=(long?exit-p.entry:p.entry-exit)*p.qty,cost=netClose(p,exit,gross);closed.push({...p,exit,...cost,closedAt:new Date().toISOString(),exitReason:'LOCK/ATR TRAIL',execution:'Trailing SL after TP1'});return null");
s=s.replace("return{...p,current:px,pnl:(long?px-p.entry:p.entry-px)*p.qty,stage,sl,tp1,finalTp,risk:entryRisk,highest,lowest}","return{...p,current:px,pnl:costAdjustedOpenPnl(p,px),stage,sl,tp1,finalTp,risk:entryRisk,highest,lowest}");
s=s.replace("return{...p,current:px,pnl:(long?px-p.entry:p.entry-px)*p.qty,stage,sl,tp1,finalTp,risk:entryRisk,highest,lowest,trailDist:dist,status:'TRAILING'}","return{...p,current:px,pnl:costAdjustedOpenPnl(p,px),stage,sl,tp1,finalTp,risk:entryRisk,highest,lowest,trailDist:dist,status:'TRAILING'}");
fs.writeFileSync(path,s);
console.log('Live cost model patched');